import { createInsertSchema, createSelectSchema, createUpdateSchema } from "drizzle-zod"
import type { Table } from "drizzle-orm"
import { z } from "zod"

/**
 * Converts an array of column names into a Zod `.omit()` mask,
 * e.g. `['id', 'createdAt']` → `{ id: true, createdAt: true }`.
 */
function toOmitMask(keys: string[]): Record<string, true> {
  return Object.fromEntries(keys.map((k) => [k, true as const]))
}

/**
 * Classifies the columns of a Drizzle table into semantic categories and
 * derives six Zod schemas suited to different layers of the application.
 *
 * ---
 *
 * ### Column categories
 *
 * - **`system`** — Values generated automatically by the DB or application
 *   infrastructure (e.g. `id`, `createdAt`, `updatedAt`). Clients can *read*
 *   these but nobody writes them explicitly. They appear in API responses but
 *   never in request bodies.
 *
 * - **`clientHidden`** — Columns owned entirely by server business logic
 *   (e.g. `userId`, `srsLevel`, `nextScheduledAt`). They are *never* surfaced
 *   to the client — not in responses, not in requests. The server can freely
 *   create and update them.
 *
 * - **`createOnly`** — Immutable after creation for **both** server and client.
 *   Can be set on first insert; omitted from all update schemas (e.g. `type`
 *   when the record's fundamental nature cannot change).
 *
 * - **`clientCreateOnly`** — The client may set this on creation but cannot
 *   update it afterwards. The server retains full write access (create + update).
 *   Useful for fields the client seeds but the server later transitions
 *   (e.g. `status` on an order: client creates with `"pending"`, server updates
 *   to `"processing"` / `"shipped"`).
 *
 * ---
 *
 * ### Generated schemas
 *
 * |                  | client create | client update | server create | server update |
 * |------------------|:---:|:---:|:---:|:---:|
 * | `system`         | ✗ | ✗ | ✗ | ✗ |
 * | `clientHidden`   | ✗ | ✗ | ✓ | ✓ |
 * | `createOnly`     | ✓ | ✗ | ✓ | ✗ |
 * | `clientCreateOnly` | ✓ | ✗ | ✓ | ✓ |
 * | *(mutable)*      | ✓ | ✓ | ✓ | ✓ |
 *
 * | Schema            | Typical use                  |
 * |-------------------|------------------------------|
 * | `select`          | Server reads from DB         |
 * | `clientSelect`    | API response bodies          |
 * | `clientCreate`    | Client POST request bodies   |
 * | `clientUpdate`    | Client PATCH request bodies  |
 * | `serverCreate`    | Server INSERT bodies         |
 * | `serverUpdate`    | Server UPDATE bodies         |
 *
 * ---
 *
 * @example
 * ```ts
 * const orderSchemas = createTableSchemas(orders, {
 *   system:           ['id', 'createdAt', 'updatedAt'],
 *   clientHidden:     ['customerId', 'fraudScore'],
 *   createOnly:       ['productId'],
 *   clientCreateOnly: ['status'],  // client seeds "pending"; server transitions later
 * })
 *
 * // Compose a joined response shape
 * const OrderWithItemsSchema = orderSchemas.clientSelect.extend({
 *   items: z.array(orderItemSchemas.clientSelect),
 * })
 *
 * // Derive TypeScript types
 * type Order = z.infer<typeof orderSchemas.clientSelect>
 * ```
 *
 * @param table  - The Drizzle table definition.
 * @param config - Column category configuration. Column names are validated
 *                 at compile time against the table's column set.
 */
export function createTableSchemas<
  T extends Table,
  TCol extends keyof T["$inferSelect"] & string,
>(
  table: T,
  config: {
    /**
     * Auto-generated by the DB or infrastructure. Visible to clients in
     * responses but never written explicitly by application code.
     * @example ['id', 'createdAt', 'updatedAt']
     */
    system: TCol[]
    /**
     * Managed by server business logic. Completely hidden from clients —
     * never appear in API requests or responses. Server can create and update.
     * @example ['userId', 'srsLevel', 'nextScheduledAt']
     */
    clientHidden: TCol[]
    /**
     * Immutable after creation for both server and client.
     * Can be set on first insert; omitted from all update schemas.
     * @example ['type']
     */
    createOnly?: TCol[]
    /**
     * Client may set on creation but cannot update afterwards.
     * Server retains full create + update access.
     * @example ['status']
     */
    clientCreateOnly?: TCol[]
  },
) {
  const systemMask          = toOmitMask(config.system)
  const clientHiddenMask    = toOmitMask(config.clientHidden)
  const createOnlyMask      = toOmitMask(config.createOnly ?? [])
  const clientCreateOnlyMask = toOmitMask(config.clientCreateOnly ?? [])

  /**
   * All columns, mirroring the raw DB row exactly.
   * For server-side use only — do not send this over the wire.
   */
  const select = createSelectSchema(table)

  /**
   * All columns except `clientHidden`.
   * Used as API response bodies — safe to send to clients.
   */
  // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
  const clientSelect = select.omit(clientHiddenMask as any)

  /**
   * Writable columns excluding `system` and `clientHidden`.
   * Fields with DB defaults are optional; all others are required.
   * Used to validate client POST / create request bodies.
   */
  const clientCreate = createInsertSchema(table).omit(
    // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
    { ...systemMask, ...clientHiddenMask } as any,
  )

  /**
   * Freely mutable columns only — excludes `system`, `clientHidden`,
   * `createOnly`, and `clientCreateOnly`. All fields partial, `id` required.
   * Used to validate client PATCH / update request bodies.
   */
  const clientUpdate = createUpdateSchema(table)
    .omit(
      // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
      { ...systemMask, ...clientHiddenMask, ...createOnlyMask, ...clientCreateOnlyMask } as any,
    )
    .extend({ id: z.string() })

  /**
   * All writable columns except `system` (includes `clientHidden`, `createOnly`,
   * and `clientCreateOnly`). Fields with DB defaults are optional.
   * Used to validate server-side INSERT operations.
   */
  const serverCreate = createInsertSchema(table).omit(
    // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
    systemMask as any,
  )

  /**
   * All server-writable columns except `system` and `createOnly`
   * (includes `clientHidden` and `clientCreateOnly`). All fields partial,
   * `id` required. Used to validate server-side UPDATE operations.
   */
  const serverUpdate = createUpdateSchema(table)
    // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
    .omit({ ...systemMask, ...createOnlyMask } as any)
    .extend({ id: z.string() })

  return { select, clientSelect, clientCreate, clientUpdate, serverCreate, serverUpdate }
}
