import { createInsertSchema, createSelectSchema, createUpdateSchema } from "drizzle-zod"
import type { Table } from "drizzle-orm"
import { z } from "zod"

/**
 * Converts an array of column names into a Zod `.omit()` mask,
 * e.g. `['id', 'createdAt']` → `{ id: true, createdAt: true }`.
 */
function toOmitMask(keys: string[]): Record<string, true> {
  return Object.fromEntries(keys.map((k) => [k, true as const]))
}

/**
 * Classifies the columns of a Drizzle table into semantic categories and
 * derives four Zod schemas suited to different layers of the application.
 *
 * ---
 *
 * ### Column categories
 *
 * - **`system`** — Values generated automatically by the DB or application
 *   infrastructure (e.g. `id`, `createdAt`, `updatedAt`). Clients can *read*
 *   these but nobody writes them explicitly. They appear in API responses but
 *   never in request bodies.
 *
 * - **`serverOnly`** — Columns owned entirely by server business logic
 *   (e.g. `userId`, `srsLevel`, `nextScheduledAt`). They are *never* surfaced
 *   to the client — not in responses, not in requests. Typically populated
 *   from the auth session or internal algorithms.
 *
 * - **`createOnly`** — Columns the client may supply when creating a record
 *   but that are locked after creation (e.g. `type`). Omitted from update
 *   request schemas.
 *
 * ---
 *
 * ### Generated schemas
 *
 * | Schema          | Includes                                    | Typical use          |
 * |-----------------|---------------------------------------------|----------------------|
 * | `select`        | All columns                                 | Server reads from DB |
 * | `clientSelect`  | All except `serverOnly`                     | API response bodies  |
 * | `clientCreate`  | All except `system` + `serverOnly`          | POST request bodies  |
 * | `clientUpdate`  | All except `system` + `serverOnly` + `createOnly`, all partial, `id` required | PATCH request bodies |
 *
 * ---
 *
 * @example
 * ```ts
 * const orderSchemas = createTableSchemas(orders, {
 *   system:     ['id', 'createdAt', 'updatedAt'],
 *   serverOnly: ['customerId', 'fraudScore'],
 *   createOnly: ['status', 'productId'],
 * })
 *
 * // Compose a joined response shape
 * const OrderWithItemsSchema = orderSchemas.clientSelect.extend({
 *   items: z.array(orderItemSchemas.clientSelect),
 * })
 *
 * // Derive TypeScript types
 * type Order = z.infer<typeof orderSchemas.clientSelect>
 * ```
 *
 * @param table     - The Drizzle table definition.
 * @param config    - Column category configuration. Column names are validated
 *                    at compile time against the table's column set.
 */
export function createTableSchemas<
  T extends Table,
  TCol extends keyof T["$inferSelect"] & string,
>(
  table: T,
  config: {
    /**
     * Auto-generated by the DB or infrastructure. Visible to clients in
     * responses but never written explicitly by application code.
     * @example ['id', 'createdAt', 'updatedAt']
     */
    system: TCol[]
    /**
     * Managed by server business logic. Completely hidden from clients —
     * never appear in API requests or responses.
     * @example ['userId', 'srsLevel', 'nextScheduledAt']
     */
    serverOnly: TCol[]
    /**
     * Client-settable on creation but immutable afterwards.
     * Omitted from update request schemas.
     * @example ['type']
     */
    createOnly?: TCol[]
  },
) {
  const systemMask = toOmitMask(config.system)
  const serverOnlyMask = toOmitMask(config.serverOnly)
  const createOnlyMask = toOmitMask(config.createOnly ?? [])

  /**
   * All columns, mirroring the raw DB row exactly.
   * For server-side use only — do not send this over the wire.
   */
  const select = createSelectSchema(table)

  /**
   * All columns except `serverOnly`.
   * Used as API response bodies — safe to send to clients.
   */
  // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
  const clientSelect = select.omit(serverOnlyMask as any)

  /**
   * Writable columns excluding `system` and `serverOnly`.
   * Fields with DB defaults are optional; all others are required.
   * Used to validate POST / create request bodies.
   */
  const clientCreate = createInsertSchema(table).omit(
    // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
    { ...systemMask, ...serverOnlyMask } as any,
  )

  /**
   * Mutable columns only (excludes `system`, `serverOnly`, and `createOnly`),
   * all fields partial, with `id` required to identify the record.
   * Used to validate PATCH / update request bodies.
   */
  const clientUpdate = createUpdateSchema(table)
    // biome-ignore lint/suspicious/noExplicitAny: omit mask keys are validated at call site via TCol generic
    .omit({ ...systemMask, ...serverOnlyMask, ...createOnlyMask } as any)
    .extend({ id: z.string() })

  return { select, clientSelect, clientCreate, clientUpdate }
}
